# -*- coding: utf-8 -*-
import base64

from odoo import http
from odoo.http import request
from odoo.tools.mimetypes import guess_mimetype
from odoo.addons.web.controllers.home import Home
from odoo.addons.web.controllers.session import Session
from odoo.addons.web.controllers.utils import ensure_db, is_user_internal
from odoo.addons.web.controllers.webmanifest import WebManifest

from ..const import get_url_prefix


def _prefix():
    if not request.db:
        return None
    return get_url_prefix(request.env)


def _debranding():
    if not request.db or 'sam.profile' not in request.env:
        return {}
    return request.env['sam.profile'].sudo()._get_debranding()


class HomeDebranding(Home):

    @http.route()
    def index(self, s_action=None, db=None, **kw):
        if request.db and request.session.uid and not is_user_internal(request.session.uid):
            return request.redirect_query('/web/login_successful', query=request.params)
        prefix = _prefix() or 'odoo'
        return request.redirect_query('/%s' % prefix, query=request.params)

    # Routes with custom prefixes are dynamically generated by
    # ir.http._generate_routing_rules (each "/odoo..." rule is duplicated
    # under the custom prefix).
    @http.route()
    def web_client(self, s_action=None, **kw):
        ensure_db()
        prefix = _prefix()
        path = request.httprequest.path
        # Old /odoo URLs (from historical emails, bookmarks, or server-generated
        # links in other modules) → permanent redirect to the new prefix.
        if prefix and (path == '/odoo' or path.startswith('/odoo/')):
            new_path = '/%s%s' % (prefix, path[len('/odoo'):])
            query = request.httprequest.query_string.decode()
            return request.redirect(
                '%s?%s' % (new_path, query) if query else new_path, code=301)
        return super().web_client(s_action=s_action, **kw)

    @http.route()
    def web_login(self, redirect=None, **kw):
        response = super().web_login(redirect=redirect, **kw)
        # Replace login page browser tab title and icon with brand config
        cfg = _debranding()
        if cfg.get('enabled') and getattr(response, 'qcontext', None) is not None:
            brand = cfg.get('brand') or request.env.company.sudo().name
            if brand:
                response.qcontext.setdefault('title', brand)
            if cfg.get('favicon'):
                response.qcontext.setdefault('x_icon', '/sam/favicon')
        return response

    def _login_redirect(self, uid, redirect=None):
        url = super()._login_redirect(uid, redirect=redirect)
        prefix = _prefix()
        if prefix and url == '/odoo':
            url = '/%s' % prefix
        return url


class DebrandingFavicon(http.Controller):

    @http.route('/sam/favicon', type='http', auth='public',
                methods=['GET'], readonly=True)
    def sam_favicon(self):
        cfg = _debranding()
        profile_id = cfg.get('favicon') and cfg.get('profile_id')
        if profile_id:
            profile = request.env['sam.profile'].sudo().browse(profile_id)
            if profile.exists() and profile.favicon:
                data = base64.b64decode(profile.favicon)
                return request.make_response(data, [
                    ('Content-Type', guess_mimetype(data, default='image/x-icon')),
                    ('Cache-Control', 'public, max-age=3600'),
                ])
        return request.redirect('/web/static/img/favicon.ico', code=302)


class SessionDebranding(Session):

    @http.route()
    def logout(self, redirect='/odoo'):
        prefix = _prefix()
        if prefix and redirect == '/odoo':
            redirect = '/%s' % prefix
        return super().logout(redirect=redirect)


class WebManifestDebranding(WebManifest):

    def _get_webmanifest(self):
        manifest = super()._get_webmanifest()
        prefix = _prefix()
        if not prefix:
            return manifest
        manifest['scope'] = '/%s' % prefix
        manifest['start_url'] = '/%s' % prefix
        for shortcut in manifest.get('shortcuts', []):
            shortcut['url'] = shortcut['url'].replace('/odoo?', '/%s?' % prefix, 1)
        return manifest

    @http.route()
    def service_worker(self):
        response = super().service_worker()
        prefix = _prefix()
        if prefix:
            response.headers['Service-Worker-Allowed'] = '/%s' % prefix
        return response

    def _get_service_worker_content(self):
        # Rewrite homepageURL("/odoo") and share_target redirect
        # ("/odoo?share_target=trigger") in service_worker.js.
        content = super()._get_service_worker_content()
        prefix = _prefix()
        if not prefix:
            return content
        return content.replace('"/odoo', '"/%s' % prefix)
